### ISSUE TITLE
AirPlay server is advertised by iOS device is not able to detect it

### ISSUE THREAD

**Issue by tobeedelafuente** [watson/airplay-mdns-server#1]
Hello! I tried to check if the AirPlay server is indeed being advertised. I used a C# application and the Zeroconf nuget package and I was able to see that the AirPlay server is indeed being advertised. Here is the following information:

Service: _airplay._tcp.local. Port: 7000, PropertySets: 1
## Begin Property Set #0

deviceid = XX-XX-XX-XX-XX-XX
features = 0x39F7
model = AppleTV2,1
## srcvers = 130.14

As far as I know the TXT record is correct. However I am not sure why my iOS 9 device is not able to detect this as an AirPlay server. Am I missing something here?

**Comment by watson** [comment]
@TerenceAnton iOS will also check if a RAOP server is being advertised with the same name (even if you don't need it in your specific setup). If you only advertise the AirPlay server and not the RAOP server, iOS will think you're trying to cheat and ignore it all together.

In case you don't actually need a RAOP server, you can just advertise a non-existing server in order for iOS to properly detect the AIrPlay server. For this you can use the [raop-stub](https://github.com/watson/raop-stub) module - it will not actually make a server, but just fake it on the network.

Are you using airplay-mdns-server as part of something you're building your self or is it just a dependency of another module you're using?

**Comment by tobeedelafuente** [comment]
Thanks @watson for pointing out the RAOP server. I totally missed that. I will try the [raop-stub](https://github.com/watson/raop-stub) and see if my device will be able to pick it up.

I am actually trying to make an AirPlay receiver on a browser. I took a look at this [documentation](https://nto.github.io/AirPlay.html#servicediscovery-airplayservice) and I was just on the AirPlay service advertisement part. I did not know that I also need the RAOP server. I will let you know about my progress.

I also apologize for posting this as an issue, I just wanted to ask a question :)

**Comment by watson** [comment]
@TerenceAnton No problem :smiley: I'm glad to help. Just re-open the issue if raop-stub doesn't solve your problem :smiley:

**Comment by watson** [comment]
@TerenceAnton Btw, I'm curious about your approach for getting mdns working in the browser. Is you code on github?

**Comment by tobeedelafuente** [comment]
@watson it worked! :smiley: so my device is able to detect it. Kudos to you btw for airplay mdns server and raop stub :smiley: 

My problem right now is how to screen mirror my device to the browser. As of now I have no approach yet on how to go about this. I am wondering if the raop-stub can be used to acquire the screen mirror of the device, or I should use something different for this.

As for my approach for getting the mdns working on the browser, hmmm... I am still clueless.

**Comment by watson** [comment]
@TerenceAnton I've not yet tried to do anything with screen mirroring part of the protocol, but I'm pretty sure RAOP doesn't play a role in screen mirroring - as far as I know that's only related to the AirPlay part of the protocol.

**Comment by tobeedelafuente** [comment]
@watson alright. Looks like the screen mirroring thing is a completely different thing. I will let you know if I will be able to do the screen mirroring :smile:

**Comment by tobeedelafuente** [comment]
@watson, I want to inform you that on my tests the airplay server and the raop stub worked on iOS 8 but did not on iOS 9. It seems that something has changed for iOS 9. 

I checked AirServer and it seems that the TXT record is different from yours. Maybe that's what caused the issue.

**Comment by watson** [comment]
@TerenceAnton iOS is pretty picky when it comes to the contents of the TXT record. ~~I'm not sure if this works for screen sharing, but for audio streaming this TXT record is verified to work on iOS 9: https://github.com/watson/raop-rtsp-server/blob/87a6e42309c3474b5bd2d570953eb51f6472ed00/index.js#L36-L53~~

**Update:** My bad, AirPlay of cause uses a different TXT record than RAOP, so the above one will not help you. I'll see if I can find time to look into it though
